DECLARE @anio int
SELECT @anio = 2013
DECLARE @fecha_desde varchar(10)
DECLARE @fecha_hasta varchar(10)

SELECT @fecha_desde =  CONCAT('01/01/',@anio)
SELECT @fecha_hasta =  CONCAT('01/12/',@anio)

--INSERT INTO
--	SUELDOS.dbo.PruebasAge
--	     ([PlantaTipo]
--           ,[NroCOntrol] 
--           ,[LugarPago]
--           ,[Escuela]
--           ,[Escalafon]
--           ,[Agru]
--           ,[tramo]
--           ,[Apertura]
--           ,[Categoria]
--           ,[HsCat]
--           ,[Juris]
--           ,[Prog]
--           ,[SubP]
--           ,[Actividad]
--           ,[Nombre]
--           ,[Cuil]
--           ,[TipoDOc]
--           ,[FechaNac]
--           ,[Sexo]
--           ,[EstadoCivil]
--           ,[FechaIngreso]
--           ,[Anios]
--           ,[Meses]
--           ,[DiasMultaAntig]
--           ,[AniosAntig]
--           ,[Ad.Prof/Perm.cgo]
--           ,[NumeroCarnet]
--           ,[AporteIOSEP]
--           ,[AporteOsocNac]
--           ,[Jubilado]
--           ,[AportePrevisional]
--           ,[SituRev]
--           ,[Interinato]
--           ,[SituRevDoc]
--           ,[Nopres/RiesgoVida]
--           ,[FechaBaja]
--           ,[FechaLiquidacion]
--           ,[MesAnioLiq]
--           ,[DiasTrabajados]
--           ,[DiasNoTrabajados]
--           ,[ImponibleANSES]
--           ,[Imponible]
--           ,[HaberS/aporte]
--           ,[HaberC/aporte]
--           ,[TotalHaberes]
--           ,[TotalDescuentos]
--           ,[Liquido]
--           ,[CantItemsOcupados]
--           ,[SalarioFamiliar]
--           ,[TotalSinCargosAlHaber]
--           ,[RemuneracionOit]
--           ,[NuevoTotalHaberes]
--           ,[AsistenciaPerfecta]
--           ,[RiesgoDeVida]
--           ,[JubRetActivo]
--           ,[Fonid]
--           ,[Activo]
--           ,[cargarNovedades]
--           ,[Legajo]
--           ,[Bloqueo])
SELECT 
			[PlantaTipo]
           ,[NroCOntrol]
           ,[LugarPago]
           ,[Escuela]
           ,[Escalafon]
           ,[Agru]
           ,[tramo]
           ,[Apertura]
           ,[Categoria]
           ,[HsCat]
           ,[Juris]
           ,[Prog]
           ,[SubP]
           ,[Actividad]
           ,[Nombre]
           ,[Cuil]
           ,[TipoDOc]
           ,[FechaNac]
           ,[Sexo]
           ,[EstadoCivil]
           ,[FechaIngreso]
           ,[Anios]
           ,[Meses]
           ,[DiasMultaAntig]
           ,[AniosAntig]
           ,[Ad.Prof/Perm.cgo]
           ,[NumeroCarnet]
           ,[AporteIOSEP]
           ,[AporteOsocNac]
           ,[Jubilado]
           ,[AportePrevisional]
           ,[SituRev]
           ,[Interinato]
           ,[SituRevDoc]
           ,[Nopres/RiesgoVida]
           ,[FechaBaja]
           ,[FechaLiquidacion]
           ,[MesAnioLiq]
           ,[DiasTrabajados]
           ,[DiasNoTrabajados]
           ,[ImponibleANSES]
           ,[Imponible]
           ,[HaberS/aporte]
           ,[HaberC/aporte]
           ,[TotalHaberes]
           ,[TotalDescuentos]
           ,[Liquido]
           ,[CantItemsOcupados]
           ,[SalarioFamiliar]
           ,[TotalSinCargosAlHaber]
           ,[RemuneracionOit]
           ,[NuevoTotalHaberes]
           ,[AsistenciaPerfecta]
           ,[RiesgoDeVida]
           ,[JubRetActivo]
           ,[Fonid]
           ,[Activo]
           ,[cargarNovedades]
           ,[Legajo]
           ,[Bloqueo]
FROM	
	LiquidacionSueldos.dbo.PruebasAge
WHERE 
	FechaLiquidacion >= @fecha_desde
AND FechaLiquidacion <= @fecha_hasta

delete from 	LiquidacionSueldos.dbo.PruebasAge
where MesAnioLiq = '01/13'

delete from ConceptoTemporal
where ageId = 6848863